name: Deploy to Hostinger via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wangyucode/sftp-upload-action@v1.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: ./
          remoteDir: ${{ secrets.SFTP_TARGET }}
          args: '-o StrictHostKeyChecking=no' 